spring.application.name=springDataJpaPractice
spring.datasource.url=jdbc:postgresql://localhost:5432/JpaPractice

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=none

spring.jpa.show.sql=true
spring.jpa.properties.hibernate.formate_sql=true

